# Site settings
baseurl = "http://jaredhuling.org/blog/"
relativeurls = true
themesDir = "themes"
languageCode = "en-us"
title = "Jared Huling"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-49091606-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""


# Added to theme
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
[permalinks]
    post = "/:year/:month/:day/:title/"

[params]
	name = "Jared Huling"
	#description = "Describe your website"
	#bio = "Blogger & Programmer"
	# Enter optionally your twitter account
	#twitter = "Your Twitter account"
	enableRSS = true
	
	fullURL = "http://jaredhuling.org/blog"
    githubContentURL = "https://github.com/jaredhuling/blog/edit/source/content/"

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	#aboutAuthor = "I'm an blogger."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    #twitter  = "https://www.twitter.com/"
    #facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/jaredhuling"
    #dribble  = "https://www.dribbble.com/"

[outputs]
home = [ "HTML", "RSS", "RFEED"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[outputFormats.RFEED]
mediatype = "application/rss"
baseName = "feed_r"
noUgly = true
